name: Release
on:
  push:
    tags:
      - "**"

jobs:
  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_ACCESS_TOKEN }}
        run: yarn electron-forge publish

  publish_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Add MacOS Certs
        run: chmod +x ./scripts/add-osx-cert.sh && ./scripts/add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_OSX_PASSWORD: ${{ secrets.CERTIFICATE_OSX_PASSWORD }}
      - name: Install dependencies
        run: yarn install
      - name: Publish
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.RELEASES_ACCESS_TOKEN }}
        run: yarn electron-forge publish

  publish_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_ACCESS_TOKEN }}
        run: yarn electron-forge publish
